### ISSUE TITLE
[MEJB-25] Classifiers do not work during deploy phase

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-ejb-plugin#61]
**[Tim Meighen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmeighen)** opened **[MEJB-25](https://issues.apache.org/jira/browse/MEJB-25?redirect=false)** and commented

Classifiers work fine during a mvn install, but during mvn deploy the build fails.  I believe that this is due to the artifact being added as an attachment without building the "non-classifier" version (i.e. there is no artifact defined).

I've attached a sample project to demonstrate.  You will need to fill in the URL to your snapshot repo

---

**Affects:** 2.1

**Attachments:**
- [classifier-test.tar.gz](https://issues.apache.org/jira/secure/attachment/12715706/classifier-test.tar.gz) (_713 bytes_)

**Issue Links:**
- [MWAR-103](https://issues.apache.org/jira/browse/MWAR-103) Classifiers do not work during deploy phase

- [MDEPLOY-45](https://issues.apache.org/jira/browse/MDEPLOY-45) Classifier not supported by deploy:deploy
 (_**"depends upon"**_)

9 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Tim Meighen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmeighen)** commented

Here's the output from a "mvn deploy":

[INFO]------------------------------------------------------------------------
[ERROR]BUILD ERROR
[INFO]------------------------------------------------------------------------
[INFO]Error deploying artifact: /Users/tmeighen/classifier-test/target/classes (No such file or directory)
[INFO]------------------------------------------------------------------------
[INFO]Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: /Users/tmeighen/classifier-test/target/classes (No such file or directory)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:635)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:551)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:530)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:309)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:276)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:393)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:760)
at org.codehaus.mevenide.netbeans.execute.MavenJavaExecutor.run(MavenJavaExecutor.java:257)
at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:131)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: /Users/tmeighen/classifier-test/target/classes (No such file or directory)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:174)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:610)
... 10 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: /Users/tmeighen/classifier-test/target/classes (No such file or directory)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:95)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162)
... 12 more
Caused by: java.io.FileNotFoundException: /Users/tmeighen/classifier-test/target/classes (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(FileInputStream.java:106)
at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:820)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:74)
... 13 more
[INFO]------------------------------------------------------------------------
[INFO]Total time: 2 seconds
[INFO]Finished at: Mon Feb 19 18:02:21 PST 2007
[INFO]Final Memory: 63M/115M
[INFO]------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Stefan Hübner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stefanhuebner)** commented

Same thing happens here. Not just with EAR-artifacts, but with WAR-artifacts too. This is very distracting.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

See issue in the deploy plugin.
