### ISSUE TITLE
[MEJB-44] artifact org.apache.maven.plugins

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-ejb-plugin#74]
**[chandrashekar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ubsuser)** opened **[MEJB-44](https://issues.apache.org/jira/browse/MEJB-44?redirect=false)** and commented

U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr>mvn clean install -e
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Reactor build order:
  [INFO]   Maven Quick Start Archetype
  [INFO]   Unnamed - olutilities:olutilities:jar:1.0
  [INFO]   Unnamed - Pil_Winrunner:Pil_Winrunner:jar:1.0
  [INFO]   Unnamed - Pil_WinrunnerEJB:Pil_WinrunnerEJB:ejb:1.0
  [INFO]   Unnamed - Pil_WinrunnerEAR:Pil_WinrunnerEAR:ear:1.0
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] Building Maven Quick Start Archetype
  [INFO]    task-segment: [clean, install]
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] artifact org.apache.maven.plugins:maven-clean-plugin: checking for update
  s from xtools-central
  [WARNING] repository metadata for: 'artifact org.apache.maven.plugins:maven-clea
  n-plugin' could not be retrieved from repository: xtools-central due to an error
  : Error transferring file
  [INFO] Repository 'xtools-central' will be blacklisted
  [INFO] [clean:clean]
  [INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\target
  [INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\target\classes

[INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\target\test-cl
asses
[INFO] [site:attach-descriptor]
[INFO] [install:install]
[INFO] Installing U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\pom.xml to C:\Document
s and Settings\marigoch\.m2\repository\PIL_WrOL\PIL_WrOL\1.0\PIL_WrOL-1.0.pom
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Building Unnamed - olutilities:olutilities:jar:1.0
[INFO]    task-segment: [clean, install]
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] artifact org.apache.maven.plugins:maven-ejb-plugin: checking for updates
from xtools-central
[WARNING] repository metadata for: 'artifact org.apache.maven.plugins:maven-ejb-
plugin' could not be retrieved from repository: xtools-central due to an error:
Error transferring file
[INFO] Repository 'xtools-central' will be blacklisted
[INFO] [clean:clean]
[INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\olutilities\ta
rget
[INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\olutilities\ta
rget\classes
[INFO] Deleting directory U:\LDN_DATA_RKYC\PilWR\OLayerEJB\Pil_Wr\olutilities\ta
rget\test-classes
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
Downloading: http://hammer.swissbank.com:5201/runtimeRepo/core/core/1.0/core-1.0
.pom
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: core:core

Reason: Error getting POM for 'core:core' from the repository: Error transferrin
g file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency
information: Unable to read the metadata file for artifact 'core:core:jar': Err
or getting POM for 'core:core' from the repository: Error transferring file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

core:core:jar:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)
Path to dependency:
1) olutilities:olutilities:jar:1.0

   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa

ultLifecycleExecutor.java:551)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:58)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:60)
at java.lang.reflect.Method.invoke(Method.java:391)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unabl
e to get dependency information: Unable to read the metadata file for artifact '
core:core:jar': Error getting POM for 'core:core' from the repository: Error tra
nsferring file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

core:core:jar:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)
Path to dependency:
1) olutilities:olutilities:jar:1.0

   at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(D

efaultArtifactCollector.java:297)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(D
efaultArtifactCollector.java:67)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:223)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:211)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:182)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDepende
ncies(DefaultPluginManager.java:1117)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:366)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:534)
... 17 more
Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
: Unable to read the metadata file for artifact 'core:core:jar': Error getting P
OM for 'core:core' from the repository: Error transferring file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

    at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenM

etadataSource.java:131)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(D
efaultArtifactCollector.java:275)
... 24 more
Caused by: org.apache.maven.project.ProjectBuildingException: Error getting POM
for 'core:core' from the repository: Error transferring file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepo

sitory(DefaultMavenProjectBuilder.java:501)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromReposito
ry(DefaultMavenProjectBuilder.java:225)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenM
etadataSource.java:102)
... 25 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Error
transferring file
core:core:pom:1.0

from the specified remote repositories:
xtools-central (http://hammer.swissbank.com:5201/runtimeRepo),
central (http://repo1.maven.org/maven2),
xtools-hufs (http://hammer.swissbank.com:5201/hufsRepo)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De

faultArtifactResolver.java:140)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De
faultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepo
sitory(DefaultMavenProjectBuilder.java:467)
... 27 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring fi
le
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputD
ata(LightweightHttpWagon.java:99)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(D
efaultWagonManager.java:369)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(Def
aultWagonManager.java:282)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(Def
aultWagonManager.java:244)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De
faultArtifactResolver.java:124)
... 29 more
Caused by: java.net.SocketException: Operation timed out: connect:could be due t
o invalid address
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:336)
at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:201)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
at java.net.Socket.connect(Socket.java:478)
at java.net.Socket.connect(Socket.java:428)
at sun.net.NetworkClient.doConnect(NetworkClient.java:158)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:646)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:336)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:297)
at sun.net.www.http.HttpClient.New(HttpClient.java:369)
at sun.net.www.http.HttpClient.New(HttpClient.java:350)
at sun.net.www.http.HttpClient.New(HttpClient.java:345)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:562)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:539)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:667)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputD
ata(LightweightHttpWagon.java:85)
... 34 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 12 seconds
[INFO] Finished at: Tue Sep 08 05:49:07 BST 2009
[INFO] Final Memory: 8M/19M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> Caused by: java.net.SocketException: Operation timed out: connect:could be due to invalid address
> I don't see how a problem with the network on your side is related to the EJB Plugin.

For questions regarding configuration, you should try the [user mailing list](http://maven.apache.org/mail-lists.html) first.
